# Указываем базовый образ
FROM python:3.10

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файл, который мы запускаем в CMD
COPY . .

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Устанавливаем переменную окружения PYTHONPATH
ENV PYTHONPATH=$PYTHONPATH:/app

# Запускаем ваше приложение
CMD ["python3", "App/Parser/ParserSpamPlugin.py"]
                 
