"""init

Revision ID: 04dd8a957f8a
Revises:
Create Date: 2023-09-18 20:08:45.114285

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "04dd8a957f8a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_file_path", sa.String(), nullable=False),
        sa.Column("target_chat", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("advertising_channels", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounts")
    # ### end Alembic commands ###
