"""empty message

Revision ID: 0a340e2695de
Revises: bf118b3b2057
Create Date: 2024-02-06 17:05:48.935580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a340e2695de'
down_revision: Union[str, None] = 'bf118b3b2057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts_inst', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts_inst', 'status')
    # ### end Alembic commands ###
