"""Migrations has been initialized successfully

Revision ID: 34f94780bf86
Revises: 455e1e1eb96b
Create Date: 2024-03-09 14:22:06.739878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f94780bf86'
down_revision: Union[str, None] = '455e1e1eb96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
