"""empty message

Revision ID: 3a9eb3ec4f75
Revises: 0a340e2695de
Create Date: 2024-02-08 18:37:58.376530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9eb3ec4f75'
down_revision: Union[str, None] = '0a340e2695de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('account_inst_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_inst_id'], ['accounts_inst.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts_inst', sa.Column('reels_link', sa.String(), nullable=True))
    op.add_column('accounts_inst', sa.Column('delay', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts_inst', 'delay')
    op.drop_column('accounts_inst', 'reels_link')
    op.drop_table('proxy')
    # ### end Alembic commands ###
