"""v5

Revision ID: 448fdec3be73
Revises: d6f8b0118b7a
Create Date: 2023-09-19 12:20:53.414864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448fdec3be73'
down_revision = 'd6f8b0118b7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'prompt')
    # ### end Alembic commands ###
