"""Migrations has been initialized successfully

Revision ID: 455e1e1eb96b
Revises: 935b7f6c344a
Create Date: 2024-03-08 19:17:16.961913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455e1e1eb96b'
down_revision: Union[str, None] = '935b7f6c344a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
