"""v6

Revision ID: 5160054694c2
Revises: 448fdec3be73
Create Date: 2023-09-20 21:51:52.388891

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "5160054694c2"
down_revision = "448fdec3be73"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
