"""empty message

Revision ID: 56e3a50958d2
Revises: f321097b2068
Create Date: 2024-02-04 15:27:04.981448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e3a50958d2'
down_revision: Union[str, None] = 'f321097b2068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_file_path', sa.String(), nullable=False),
    sa.Column('target_channels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium_chat_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('account_stories_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_stories_id'], ['accounts_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premium_chat_members')
    op.drop_table('accounts_stories')
    # ### end Alembic commands ###
