"""v2

Revision ID: 6aad6bacee6d
Revises: 04dd8a957f8a
Create Date: 2023-09-18 21:05:28.521090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aad6bacee6d'
down_revision = '04dd8a957f8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
