"""add forigien key

Revision ID: 75d15c074f9f
Revises: 12345678
Create Date: 2024-01-08 13:30:15.049429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d15c074f9f'
down_revision: Union[str, None] = '12345678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_chat_members', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'telegram_chat_members', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_chat_members', type_='foreignkey')
    op.drop_column('telegram_chat_members', 'account_id')
    # ### end Alembic commands ###
