"""empty message

Revision ID: 935b7f6c344a
Revises: 3a9eb3ec4f75
Create Date: 2024-02-11 10:33:53.150028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935b7f6c344a'
down_revision: Union[str, None] = '3a9eb3ec4f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts_tg', sa.Column('delay', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts_tg', 'delay')
    # ### end Alembic commands ###
