"""v3

Revision ID: 99fa4c7a93e9
Revises: 6aad6bacee6d
Create Date: 2023-09-18 21:49:41.207675

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "99fa4c7a93e9"
down_revision = "6aad6bacee6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accounts", "target_chat", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accounts", "target_chat", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
