"""empty message

Revision ID: bf118b3b2057
Revises: e0da2999fb2e
Create Date: 2024-02-05 15:23:12.804805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf118b3b2057'
down_revision: Union[str, None] = 'e0da2999fb2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts_inst', sa.Column('target_channels', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('accounts_inst', 'target_channel')
    op.add_column('followers', sa.Column('target_channel', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'target_channel')
    op.add_column('accounts_inst', sa.Column('target_channel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('accounts_inst', 'target_channels')
    # ### end Alembic commands ###
