"""empty message

Revision ID: c956789ed4b3
Revises: 412e9a0220ea
Create Date: 2024-02-04 14:33:17.095346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c956789ed4b3'
down_revision: Union[str, None] = '412e9a0220ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_file_path', sa.String(), nullable=False),
    sa.Column('target_channels', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium_chat_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('account_stories_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_stories_id'], ['accounts_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('target_channels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_channels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('premium_members', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='target_channels_pkey')
    )
    op.drop_table('premium_chat_members')
    op.drop_table('accounts_stories')
    # ### end Alembic commands ###
