"""v4

Revision ID: d6f8b0118b7a
Revises: 99fa4c7a93e9
Create Date: 2023-09-18 22:07:41.987544

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d6f8b0118b7a"
down_revision = "99fa4c7a93e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("status", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "status")
    # ### end Alembic commands ###
