"""empty message

Revision ID: e0da2999fb2e
Revises: 49fb10d64fa8
Create Date: 2024-02-05 14:05:45.911945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0da2999fb2e'
down_revision: Union[str, None] = '49fb10d64fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('premium_chat_members', sa.Column('target_channel', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('premium_chat_members', 'target_channel')
    # ### end Alembic commands ###
