"""Migrations has been initialized successfully

Revision ID: e992811cc4fc
Revises: cf1c54a452e7
Create Date: 2024-03-09 14:32:27.632304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e992811cc4fc'
down_revision: Union[str, None] = 'cf1c54a452e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
