"""empty message

Revision ID: f321097b2068
Revises: c956789ed4b3
Create Date: 2024-02-04 15:24:03.828841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f321097b2068'
down_revision: Union[str, None] = 'c956789ed4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premium_chat_members')
    op.drop_table("accounts_stories")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts_stories', 'status')
    # ### end Alembic commands ###
